// <auto-generated />
namespace task3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserRoleFieldRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRoleFieldRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201507211506397_User-Role-Field-Rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
